title: Azgard Modpack
description: Guías, changelogs y soporte
remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
  - jekyll-remote-theme

# habilita CSS del sitio
site-css: /assets/css/custom-styles.css